version: "2"
services:
  shopping-cart-api:
    build: .
    container_name: shopping-cart-api
    depends_on:
      - shopping-cart-db
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - ${APP_PORT}:${APP_PORT}

  shopping-cart-db:
    image: mysql:5.7
    container_name: shopping-cart-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysqldbdata:/var/lib/mysql

volumes:
  mysqldbdata:
